// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Project struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type ProjectAPI struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Path   string `json:"path"`
	Type   string `json:"type"`
	Result string `json:"result"`
}
